CREATE TABLE ACTIVITIES (
ACTIVITY_ID INTEGER PRIMARY KEY,
ACTIVITY_NAME TEXT NOT NULL,
ACTIVITY_TYPE TEXT NOT NULL,
PARTICIPANTS INTEGER,
FEE INTEGER
);

INSERT INTO ACTIVITIES (ACTIVITY_ID,ACTIVITY_NAME,ACTIVITY_TYPE,PARTICIPANTS,FEE) VALUES
(1, 'Yoga Class','Fitness', 20, 500),
(2, 'Dance Class','Arts', 15, 400),
(3, 'Football','Sports', 30, 300),
(4, 'Painting','Arts', 10, 350),
(5, 'Zumba','Fitness', 25, 320),
(6, 'Basketball','Sports', 20, 350),
(7, 'Music Class','Arts', 12, 500),
(8, 'Swimming','Sports', 18, 600);

SELECT * FROM ACTIVITIES;

--PART:1--
SELECT ACTIVITY_NAME ,FEE FROM ACTIVITIES ORDER BY FEE DESC;
SELECT ACTIVITY_NAME ,FEE FROM ACTIVITIES ORDER BY FEE ASC;

SELECT ACTIVITY_NAME,PARTICIPANTS,FEE FROM ACTIVITIES ORDER BY PARTICIPANTS ASC,FEE DESC;

--PART:2--
SELECT ACTIVITY_NAME, PARTICIPANTS FROM ACTIVITIES ORDER BY PARTICIPANTS DESC LIMIT 5;

--PART:4--
SELECT PARTICIPANTS, COUNT(*) AS PARTICIPANTS_COUNTED
FROM ACTIVITIES
GROUP BY PARTICIPANTS
HAVING COUNT(*) > 1;

SELECT ACTIVITY_NAME , AVG(FEE) AS AVERAGE_FEE
FROM ACTIVITIES
GROUP BY ACTIVITY_NAME
HAVING AVG(FEE) >= 400;